#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Lorenzo Israel'
        hostname: ubuntu-los
        username: losUbuntu
        password: '$y$j9T$uhkxlm8nUQaNu.6rl4k2d.$DIldpYy96OHg8lFjfXfc671BZcGWkPOmaDONGAhGSg3'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - chromium-browser
        - gimp
        - git
        - wget
        - shotcut
        - code
        - audacity
        - echo
    snaps:
        - name: lunacy
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    
