#cloud-config
autoinstall:
    version: 1
    identity:
        realname: 'Lorenzo Israel'
        hostname: ubuntu-los
        username: losUbuntu
        password: '$6$4MgG7FdJHzUu$d5VZ5bW.9v8WrOeVY1T2Xo6l9Q1n7j0qXHJmzL4bN8cB3kS5VfE2RxGhC7vIyKZaP1sD3eW4rT6uY9H0'
    locale: pt_BR.utf8
    keyboard:
        layout: br
    timezone: "America/Sao_Paulo"   
    packages:
        - libreoffice
        - chromium-browser
        - gimp
        - git
        - wget
        - shotcut
        - code
        - audacity
        - echo
    snaps:
        - name: lunacy
          channel: stable
          classic: false
    codecs:
        install: true
    drivers:
        install: true
    updates: all
    shutdown: reboot
    
